name: Generate Podcast Feeds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: podcast-generator:latest

      - name: Run Feed Generator
        uses: docker://podcast-generator:latest
        with:
          args: ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
